spring.application.name=Portfolio
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=postgres
spring.datasource.password=Manu@2003

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.jpa.show-sql=true